disabled_rules:
  - trailing_whitespace
  - nesting
  - number_separator
  - comment_spacing

opt_in_rules:
  - vertical_parameter_alignment_on_call
  - operator_usage_whitespace
  - let_var_whitespace
  - empty_string
  - closure_spacing
  - closure_end_indentation
  - sorted_imports
  - redundant_type_annotation
  - file_name
  - file_name_no_space
  - empty_count
  - vertical_whitespace_opening_braces
  - vertical_whitespace_closing_braces
  
excluded:
  - Pods
  - FancyMouse/Application/AppDelegate.swift
  - FancyMouse/Application/SceneDelegate.swift
  - FancyMouseTests
  - FancyMouseUITests

force_cast: error # 너무 타이트하면 warning으로 바꿔도 됨
force_try:
  severity: error
  
line_length: 100
  
file_length:
  error: 300 # 10-200룰이란게 있는데, 우리는 조금 완화해서 하나의 파일에 최대 300줄 까지로 해보자!

type_name:
  min_length:
    error: 3
  max_length:
    warning: 40
  excluded: iPhone
identifier_name:
  min_length:
    error: 3
  excluded:
    - id
    - URL
    - GlobalAPIKey
reporter: "xcode"
