disabled_rules:
  - line_length
  - trailing_whitespace
  - nesting
  - redundant_type_annotation
  - number_separator
  - object_literal
  - file_name
  - sorted_imports

opt_in_rules:
  - empty_count
  - vertical_whitespace_opening_braces
  - vertical_whitespace_closing_braces
  
excluded:
  - Pods
  - FancyMouse/AppDelegate.swift
  - FancyMouse/SceneDelegate.swift
  - FancyMouseTests
  - FancyMouseUITests

force_cast: error # 너무 타이트하면 warning으로 바꿔도 됨
force_try:
  severity: error
  
file_length:
  error: 300 # 10-200룰이란게 있는데, 우리는 조금 완화해서 하나의 파일에 최대 300줄 까지로 해보자!

type_name:
  min_length:
    error: 3
  max_length:
    warning: 20
  excluded: iPhone
identifier_name:
  min_length:
    error: 3
  excluded:
    - id
    - URL
    - GlobalAPIKey
reporter: "xcode"
